runtime: java17
env: standard
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2

env_variables:
  PROFILE: prod
  SPRING_DATASOURCE_URL: jdbc:mysql://host porta/ nome
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: LBEfaiQOqlAtksqXWzfVbeqWnIdDqtax
  SERVER_PORT: '8080'
