version: '3.8'

services:
  db:
    image: postgres:13.1-alpine
    container_name: db
    environment:
      - POSTGRES_DB=questmast-dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
    container_name: app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/questmast-dev
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - PROFILE=prod

    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
