spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/questmast-dev
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  flyway:
    enabled: false
    baseline-on-migrate: true