spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/questmast-dev
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: true