spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/questmast-dev}
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: egsoft502@gmail.com
    password: vzjr nnab ffwq rput
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB

jwt:
  private:
    key: classpath:app.key
  public:
    key: classpath:app.pub

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

openai:
  model: gpt-3.5-turbo
  max-completions: 1
  temperature: 0
  api:
    key: ${OPEN_AI_API_KEY}
    url-chat: https://api.openai.com/v1/chat/completions
    url-file: https://api.openai.com/v1/files

server:
  servlet:
    context-path: /api
