runtime: java17
env: standard
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2

env_variables:
  PROFILE: prod
  SPRING_DATASOURCE_URL: jdbc:postgresql://shortline.proxy.rlwy.net:18680/railway
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: WxzDcGPkvjXCEoZVCLEXHAgFvcNpqoeR
